version: '3.5'

services:
  postgres_17:
    container_name: postgres_17_NamDevOdoo
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
      POSTGRES_USER: ${db_user:-odoo}
      POSTGRES_PASSWORD: ${db_password:-odoo}
      PGDATA: /var/lib/postgresql/data  # Thay đổi đường dẫn PGDATA cho đúng với volume trong container
    volumes:
       - /mnt/c/Users/ASUS/Documents/GitHub/data/postgres:/var/lib/postgresql/data  # Đường dẫn chỉnh sửa
    ports:
      - "${db_port}:5599"
    networks:
      - postgres_17
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin_container_NamDevOdoo
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - postgres_17
    restart: unless-stopped

networks:
  postgres_17:
    driver: bridge

volumes:
  postgres_17:
